Change some code style.
hyunSo/dwg-bob-first-server pull request #1
Opened 2017-02-04 18:07 UTC by dreamchaser3

2017-02-04 18:12 UTC, dreamchaser3 commented
@cvanderw I changed the script following your comments. And, are these right in the way you suggested to me?
@hyunSo new pull request.

2017-02-05 07:09 UTC, cvanderw requested changes
Thanks for addressing the feedback! I've left a few more comments to look at before merging.

By the way, I have a general question about the server code. Where are you planning to run the server?

2017-02-05 07:09 UTC, cvanderw commented on NodejsConsoleApp1/app.js
> +//Connect to mysql db.
Small nit: Here, and elsewhere, place a single space between "//" and the start of the comment. See examples for writing comments here: https://google.github.io/styleguide/jsguide.html#formatting-comments.

For example:
`// Connect to MySQL db.`

2017-02-05 07:09 UTC, cvanderw commented on NodejsConsoleApp1/app.js
> +            //Parse json.
Same comment here about a single space after '//'.

2017-02-05 07:09 UTC, cvanderw commented on NodejsConsoleApp1/app.js
> +                    case 6://Get the user's information and send to Client.
What does '6' mean? Could this be better served as a constant?

2017-02-05 07:09 UTC, cvanderw commented on NodejsConsoleApp1/app.js
> +                    //TODO: Write all case process like 'case 6' below.
What does it mean to write all case statements like 'case 6'?

2017-02-05 07:09 UTC, cvanderw commented on NodejsConsoleApp1/app.js
>      httpServer: server
I notice you're opting to use 4 spaces instead of 2 (as recommended here https://google.github.io/styleguide/jsguide.html#formatting-block-indentation).

I think it's fine to use 4 spaces instead of 2 so long as you guys are consistent about it.

2017-02-05 07:09 UTC, cvanderw commented on NodejsConsoleApp1/app.js
> +                        sqlConnection.query(`select usn, tot_point from user_list where nickname = '${nickname}'`, function (err, rows, cols) {
This line looks super long. The style guide recommends keeping code to a column length of 80: https://google.github.io/styleguide/jsguide.html#formatting-column-limit.

If you plan to keep a 4 space indent then 80 might be a bit small, but this line 143 characters. Keep down to a limit of 100 characters at most.

2017-02-05 07:09 UTC, cvanderw commented on NodejsConsoleApp1/app.js
> +                                console.log("Wrong Parameter.");
Here and elsewhere, use single quotes for string literals: https://google.github.io/styleguide/jsguide.html#features-strings-use-single-quotes.

2017-02-05 07:09 UTC, cvanderw commented on NodejsConsoleApp1/app.js
>              console.log((new Date()) + ' Received Message from : ' + message.utf8Data);
The styleguide appears to suggest using templated strings instead of concatenation of multiple different strings: https://google.github.io/styleguide/jsguide.html#features-strings-template-strings.

Try it out and see if it's any better.

2017-02-05 07:30 UTC, dreamchaser3 commented on NodejsConsoleApp1/app.js
>              console.log((new Date()) + ' Received Message from : ' + message.utf8Data);
Yes. using templated strings is more convenient. Thanks!

2017-02-05 07:31 UTC, hyunSo commented on NodejsConsoleApp1/app.js
> +                    case 6://Get the user's information and send to Client.
The query above is about the first table (flag 6) of below document, 
https://docs.google.com/spreadsheets/d/1d9B10jpf_RB3fCiBGkL1lYiWncIxd1LxFT1yRXgY9Sw/edit
about client-server protocol. 6 means the flag of our communication protocol.

2017-02-05 07:35 UTC, dreamchaser3 commented on NodejsConsoleApp1/app.js
> +                    //TODO: Write all case process like 'case 6' below.
Oh.. sorry. Please take a look this file in our drive.
https://docs.google.com/spreadsheets/d/1d9B10jpf_RB3fCiBGkL1lYiWncIxd1LxFT1yRXgY9Sw/edit#gid=0
the '6' means flag.
We communicate between Client and Server as a **flag**.
If there is a better idea you have, please say to me.
Thanks.

2017-02-05 07:53 UTC, dreamchaser3 commented
@cvanderw Please check our reply.
And, firstly we run the server on our laptops.
If all testings are done, we think to transfer to AWS.

2017-02-05 07:58 UTC, dreamchaser3 commented
@cvanderw  And, also we changed again following your feedback.
Please check once more.
Thanks!

2017-02-05 08:37 UTC, cvanderw requested changes

2017-02-05 08:37 UTC, cvanderw commented on NodejsConsoleApp1/app.js
> +var mysql = require('mysql');// mysql module
Nit: Update the comment to use "MySQL". That's the official name.

2017-02-05 08:37 UTC, cvanderw commented on NodejsConsoleApp1/app.js
> +    console.log(`${(new Date())} Connection from origin request.origin.`);
How granular is Date()?

Optionally consider to pull out a single "new Date()" instance that is used for these logging statements. If Date() is very granular you'll have slightly different values at different log statements making debugging difficult.

2017-02-05 08:37 UTC, cvanderw commented on NodejsConsoleApp1/app.js
> +                                obj['flag'] = 6;
According to your design doc this 'flag' would have the value '1'. Is '6' correct here?

2017-02-05 08:37 UTC, cvanderw commented on NodejsConsoleApp1/app.js
> +                    case 6://Get the user's information and send to Client.
Thanks for the explanation about what '6' is! I can see that in the spreadsheet. However, I still recommend for you to write a constant that replaces this. What does '6' represent? It's the flag for requesting the user's information. So something like `userInfoRequestFlag` (or `USER_INFO_REQUEST_FLAG` depending on where the constant is defined).

This is more readable and you can then drop the comment next to "case 6" because the constant describes what it's for.

2017-02-05 08:44 UTC, hyunSo commented on NodejsConsoleApp1/app.js
> +                                obj['flag'] = 6;
The document's output message part was wrong so 6 is right in here(the query is about getting an user's information.)

2017-02-05 08:45 UTC, hyunSo commented on NodejsConsoleApp1/app.js
> +var mysql = require('mysql');// mysql module
@dreamchaser3 I modified!

2017-02-05 09:37 UTC, dreamchaser3 commented
@cvanderw My last commit message has typo..
Anyway, please check once more, Chris!
Thanks!

2017-02-05 11:31 UTC, cvanderw requested changes
This is starting to look much better! :star:

I'm still waiting for your change with respect to the constant flag value. Other than that I'm happy to approve.

@hyunSo please feel free to leave comments for this pull request and approve when you feel happy with the change.

2017-02-05 11:31 UTC, cvanderw commented on NodejsConsoleApp1/app.js
> -    console.log(`${(new Date())} Connection accepted.`);
I see you removed the date. If that's what you want to do that's fine too.

In case it wasn't clear my recommendation was to create the Date object once and reuse that same instance wherever you were previously creating a new Date.

For example:

```
var date = new Date();
// later...
console.log(`${date} Connection accepted.`);
```

But if you want to keep the Date object out that's fine too; what you have now is okay.

2017-02-05 11:43 UTC, hyunSo commented on NodejsConsoleApp1/app.js
> -    console.log(`${(new Date())} Connection accepted.`);
I feel great about the changes, so I will approve it!
We are planning to apply the constant flag values like
    const	REQUEST_USER_TREASURE_LIST_FLAG	1
    const	REQUEST_USER_MADE_GAME_FLAG	2
    const	REQUEST_USER_PARTICIPATING_GAME_LIST_FLAG	3
    const	REQUEST_GAME_JOIN_USER_LIST_FLAG	4
    const	REQUEST_GAME_TREASURE_INFO_FLAG	5
    const	REQUEST_USER_INFO_FLAG	6
	
    const	SET_USER_INFO_FLAG	11
    const	SET_GAME_INFO_FLAG	12
    const	SET_GAME_STATUS_END_FLAG	13
    const	SET_USER_JOIN_FLAG	14
    const	SET_USER_GET_TREASURE_FLAG	15
after this pull requests... 
Does it seems okay? @cvanderw

2017-02-05 11:59 UTC, cvanderw commented on NodejsConsoleApp1/app.js
> -    console.log(`${(new Date())} Connection accepted.`);
@hyunSo I'm totally fine with that.
@dreamchaser3 could you please leave a TODO comment to address the constants? Then I'll approve.

2017-02-05 12:15 UTC, hyunSo commented on NodejsConsoleApp1/app.js
> -    console.log(`${(new Date())} Connection accepted.`);
@cvanderw I leaved TODO comment for those works (with flags as a list) so please check!

2017-02-05 12:38 UTC, cvanderw approved these changes
Approving change with a few minor comments for you to consider before merging.

Great work! :thumbsup:

2017-02-05 12:38 UTC, cvanderw commented on NodejsConsoleApp1/app.js
> +//client to server
Since this is a block comment, consider providing a * lined up at the start of each line as suggested here: https://google.github.io/styleguide/jsguide.html#formatting-block-comment-style.

2017-02-05 12:38 UTC, cvanderw commented on NodejsConsoleApp1/app.js
> +/* TODO : add flags as a constant
Consider using the TODO style suggested here https://google.github.io/styleguide/jsguide.html#formatting-comments.


For example:
`TODO(dreamchaser3): Add flags as a constant.`
This makes it clear who knows what to do for the TODO.

2017-02-05 13:46 UTC, hyunSo commented
I added with * and username to comments.
Thank you for great work @dreamchaser3 and stylish comment @cvanderw !

2017-02-05 13:47 UTC, merged